routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth:web','role:Admin|Teacher'])->group(function() {
    Route::resource('/groups', GroupController::class);
    Route::resource('/exams', ExamController::class);
    Route::get('/students', 'StudentController@index')->name('students.index');
    Route::get('/student/create' , 'StudentController@create')->name('student.create');
    Route::post('student/approval/{student}', 'StudentController@approval');
    Route::post('student/store', 'StudentController@store')->name('student.store');

    Route::post('/exams/activation/{id}', 'ExamController@activation')->name('exams.activation');
    Route::get('/exams/manage/{id}', 'ExamController@manage')->name('exams.manage');
    Route::post('/exams/manage/question/list/{id?}', 'ExamController@questionList')->name('exams.manage.question.list');
    Route::post('/exams/assign-question', 'ExamController@assignQuestion')->name('exams.assignQuestion');

    Route::get('/question/create', 'QuestionController@create')->name('question.create');
    Route::post('/question/save', 'QuestionController@save')->name('question.save');
    Route::post('question/unset/{id}', 'QuestionController@unset')->name('question.unset');
    Route::get('/question/{id}/edit', 'QuestionController@edit')->name('question.edit');
    Route::post('/question/update/{question}', 'QuestionController@update')->name('question.update');
    Route::get('/question/select/{subject}', 'QuestionController@select')->name('question.select');
    Route::post('/question/set/{question}', 'QuestionController@set')->name('question.set');
    Route::delete('/question/destroy/{question}', 'QuestionController@destroy')->name('question.destroy');

    Route::get('/questions', 'QuestionController@index')->name('questions.index');
    Route::post('/select/question/set/{exam}', 'ExamController@selectQuestionSet')->name('select.question.set');

    Route::resource('/banks', BanksController::class);
    Route::get('/banks/question/select/{subject}', 'BanksController@select')->name('banks.question.select');
    Route::post('banks/question/unset/{id}', 'BanksController@unset');
    Route::post('/banks/question/unsetWhileCreate/{question}', 'BanksController@unsetWhileCreate');
    Route::post('banks/question/set/while/edit/{bank}/{question}', 'BanksController@setWhileEdit');
    Route::post('banks/question/set/while/create/{question}', 'BanksController@setWhileCreate');
    Route::get('/banks/question/select/while/create/{subject}', 'BanksController@selectWhileCreate');

    Route::post('exam/manage/question/save/', 'ExamController@examManageQuestionSave')->name('exam.manage.question.save');
    Route::post('bank/rename/{bank}', 'BanksController@rename');
    Route::get('/banks/question/select/while/edit/{bank}/{subject}', 'BanksController@selectWhileEdit');

    Route::get('/exam-students', 'StudentController@examStudents');
    Route::get('/exam-students/delete/{examStudent}', 'StudentController@examStudentsDelete');
    Route::get('/exam-students/edit/form/{examStudent}', 'StudentController@examStudentEditForm')->name('student-exam.edit.form');
    Route::get('/student/unset/from/list/{exam}/{student}', 'StudentController@studentUnsetFromList')->name('student.unset.from.list');
    Route::get('/student/add/to/exams', 'StudentController@addExamForm');
    Route::post('/student/list/from/institution/{institution}', 'StudentController@studentListFromInstitution');
    Route::post('/student/attach/to/exam/{id}', 'StudentController@attachToExam');

    Route::get('/results', 'ResultController@index');
    Route::get('/result/from/teachers/panel/{exam}', 'ResultController@resultFromTeachersPanel')->name('result.teacher');
    Route::get('/result/sheet/from/teachers/panel/{result}/{exam}/{user}', 'ResultController@resultSheetTeachersPanel')->name('result.sheet');

    Route::get('/competitions', 'CompetitionController@index');
    Route::get('/competitions/create', 'CompetitionController@create')->name('competitions.create');
    Route::post('/competitions/store', 'CompetitionController@store')->name('competitions.store');
    Route::get('/competitions/{competition}', 'CompetitionController@show')->name('competition.show');
    Route::get('/competitions/edit/{competition}', 'CompetitionController@edit')->name('competition.edit');
    Route::post('/competitions/update/{competition}', 'CompetitionController@update')->name('competition.update');
    Route::get('/competitions/delete/{competition}', 'CompetitionController@delete')->name('competition.delete');
    //Route::post('competitions/student/list/from/institution/{institution}', 'CompetitionController@studentList');
    Route::resource('/institutions', InstitutionController::class);
    Route::resource('/subjects', SubjectController::class);
});

Route::get('/register/students', 'Auth\RegisterController@showStudentRegisterForm');
Route::post('/register/students', 'Auth\RegisterController@createStudent');

Route::middleware(['auth:web','role:Admin'])->group(function() {
    Route::view('/admin', 'admin');
    Route::resource('teachers', TeacherController::class);
    Route::post('/teacher/activation/{teacher}', 'TeacherController@activation');
    Route::get('accessibility', 'AccessibilityController@index')->name('accessibility');
    Route::get('accessibility/edit/{role}', 'AccessibilityController@edit')->name('accessibility.edit');
    Route::post('accessibility/update/{role}', 'AccessibilityController@update')->name('accessibility.update');
    Route::get('permissions', 'AccessibilityController@permissions')->name('permissions');
    Route::get('add/permission', 'AccessibilityController@addPermission')->name('add.permission');
    Route::get('save/permission', 'AccessibilityController@savePermission')->name('save.permission');
    Route::get('permission/edit/{id}', 'AccessibilityController@editPermission')->name('edit.permission');
    Route::get('permission/update/{id}', 'AccessibilityController@updatePermission')->name('update.permission');
    Route::get('permission/delete/{id}', 'AccessibilityController@deletePermission')->name('delete.permission');
});

Route::middleware(['auth:web','role:Teacher|Admin|Student'])->group(function() {
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile/update/{role}/{id}', 'ProfileController@update')->name('profile.update');
});

Route::middleware(['auth:web','role:Student'])->group(function () {
    Route::get('/student', 'StudentController@getProfile')->name('profile');
    Route::get('/student/exam/attend/{exam}/{id}', 'StudentController@examAttend')->name('exam.attend');
    Route::post('result/create/{exam}/{id}', 'StudentController@resultCreate');
    Route::get('/student/results', 'StudentController@resultsList')->name('student.results');
    Route::get('/student/result/sheet/{result}/{exam}/{user}', 'StudentController@resultSheetStudentPanel')->name('student.result.sheet');
    Route::get('/student/competitions', 'StudentController@competitions');
});

//Exam enrollment
Route::get('enroll/exam/{examName}', function () {
    auth()->logout();
    return view('exams/enroll');
});
Route::post('enroll/student/frontend', 'ExamController@enrollStudentFrontend')->name('enroll.student.frontend');

//Competition enrollment
Route::get('enroll/competition/{competitionName}', function () {
    auth()->logout();
    return view('competitions/enroll');
});
Route::post('enroll/student/frontend/competition', 'CompetitionController@enrollStudentFrontend')->name('enroll.student.frontend.competition');

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $teachers = User::whereNull('institution_id')->where('is_admin',0)->get();;
      return view('teachers.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
        $request->validate([
            'name' => 'required|regex:/^([a-zA-Z]+)(\s[a-zA-Z]+)*$/',
            'email' => 'required|email|unique:users',
            'phone' => 'required|regex:/(01)[0-9]{9}/|unique:users',
            'password' => 'required|min:8|confirmed',
        ]);
        $teacher = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'password' => Hash::make($request->password)
        ]);
        $teacher->is_active=1;
        $teacher->save();
        $teacher->assignRole('Teacher');
        $permissions = \Spatie\Permission\Models\Permission::whereNotIn('name', ['manage accessibility', 'do exam'])->get();
        foreach($permissions as $permission){
            \DB::table('model_has_permissions')->insert(['permission_id'=> $permission->id, 'model_type'=> 'App\User', 'model_id'=> $teacher->id]);
        }
        \Session::flash('msg_success', 'New teacher has been created!');
        return redirect()->route('teachers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = User::find($id);
        return view('teachers.edit', compact('id', 'teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required','regex:/^([a-zA-Z]+)(\s[a-zA-Z]+)*$/'],
            'email' => ['required','email',Rule::unique('users')->ignore($id)],
            'phone' => ['required','regex:/(01)[0-9]{9}/',Rule::unique('users')->ignore($id)],
            
        ]);

        User::updateOrCreate([
            'id'=>$id
        ],
        [
            'name' => $request->name,
            'email'=>$request->email,
            'phone'=> $request->phone,
        ]);
        \Session::flash('msg_success', 'Teacher info updated!');
        return redirect()->route('teachers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        \Session::flash('msg_success', 'The teacher has been deleted!');
        return back();
    }

    public function activation(User $teacher){
        if ($teacher->is_active == 1){
            $teacher->removeRole('Teacher');
            \DB::table('model_has_permissions')->where('model_type', 'App\User')->where('model_id', $teacher->id)->delete();
            $teacher->is_active = 0;
        }else {
            $teacher->is_active = 1;
            $teacher->assignRole('Teacher');
            $permissions = \Spatie\Permission\Models\Permission::whereNotIn('name', ['manage accessibility', 'do exam'])->get();
            foreach($permissions as $permission){
                //$teacher->givePermissionTo($permission->name);
                \DB::table('model_has_permissions')->insert(['permission_id'=> $permission->id, 'model_type'=> 'App\User', 'model_id'=> $teacher->id]);
            }
        }
        $teacher->save();
    }
}

resources/views/teachers/create.blade.php
@extends('app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">

                            <form method="POST" action="{{ route('teachers.store') }}" aria-label="{{ __('Register') }}">

                                @csrf

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                    <div class="col-md-6">
                                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone No.') }}</label>

                                    <div class="col-md-6">
                                        <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" required autocomplete="phone">

                                        @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                    <div class="col-md-6">
                                        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                        @error('password')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                    <div class="col-md-6">
                                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Add') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/teachers/edit.blade.php
@extends('app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">

                            <form method="POST" action="{{ route('teachers.update', [$id]) }}" aria-label="{{ __('Update') }}">

                                @csrf @method('PATCH')

                                <div class="form-group row">
                                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $teacher->name }}" required autocomplete="name" autofocus>

                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                    <div class="col-md-6">
                                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $teacher->email }}" required autocomplete="email">

                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone No.') }}</label>

                                    <div class="col-md-6">
                                        <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $teacher->phone }}" required autocomplete="phone">

                                        @error('phone')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Update') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/teachers/index.blade.php
@extends('app')

@section('role')
    Admin
@stop

@section('header')
    Teachers
@stop

@section('content') 
    <div class="card">
        <div class="row">
            <div class="col-md-10"></div>
            <div class="col-md-1" style="top: 20px"><a href="{{route('teachers.create')}}"><button class="btn btn-info btn-block">  Add  </button></a></div>       
        </div>
        <div class="card-body" style='margin-top:7px'>
            @if(\Session::has('msg_success'))
            <div class="row">
                <div class="col-lg-10">
                    <div  class="alert">
                        <strong>Success! </strong>{{ \Session::get('msg_success') }}
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>    
            @endif
            <div class="table-responsive">
                <table class="table table-hover mx-auto table-sm">
                    <thead class="header-dark">
                        <tr>
                            <th>Name</th>
                            <th>email</th>
                            <th>Phone</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($teachers as $teacher)
                        <tr>
                            <td>{{$teacher->name}}</td>
                            <td>{{$teacher->email}}</td>
                            <td>{{$teacher->phone}}</td>
                            <td>
                                @if($teacher->is_active == 1)
                                    <button type="button" value="{{$teacher->id}}" class="activate  btn btn-danger">Deactivate</button>
                                @else
                                    <button type="button" value="{{$teacher->id}}" class="activate  btn btn-info">Activate</button>
                                @endif
                            </td>
                            <td> 
                                <i class="nav-icon fas fa-cogs gear"></i>
                                <div style='display:none' class="btn-group" role="group" aria-label="">
                                    <a href="{{route('teachers.edit',[$teacher->id])}}"><button type="button" class="btn btn btn-secondary btn-info">Edit</button></a>
                                    <span style="margin-left: 10px"></span>
                                    <form class='delete' method="post" action="{{route('teachers.destroy', [$teacher->id])}}" enctype="multipart/form-data">
                                        @csrf @method('DELETE')
                                        <button type="submit" class="btn btn btn-secondary btn-danger">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop

@section('js')
<script type="text/javascript">
    $(document).ready(function(){
        $('.activate').click(function(e){
                    e.preventDefault();
                    if ($(this).text().trim()==='Deactivate'){
                        $(this).text('Activate')
                        $(this).removeClass('activate btn btn-danger')
                        $(this).addClass('activate btn btn-info')
                    }else if ($(this).text().trim()==='Activate'){
                        $(this).text('Deactivate')
                        $(this).removeClass('activate btn btn-info')
                        $(this).addClass('activate btn btn-danger')
                    }

                    $.ajax({
                        type:'POST',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        url:'{{url('')}}'+'/teacher/activation/'+$(this).val(),
                        data:'_token = <?php echo csrf_token() ?>',
                        success:function() {

                        }
                    })
                }
            );
        });
</script>

<script>
    $(".delete").on("submit", function(){
        return confirm("Are you sure?");
    });
</script>

<script>
    $(".gear").on("click", function(){
        $(this).hide()
        $(this).next().removeAttr("style");
    });
</script>
@stop

resources/views/teachers/resultFromTeachersPanel.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card">
        <div class="card-body">
          <table class="table">
              <thead>
               <tr>
                   <td>Exam</td>
                   <td>Student</td>
                   <td>Right Answers</td>
                   <td>Wrong Answers</td>
                   <td>Answer Sheet</td>
               </tr>
              </thead>
              <tbody>
               @foreach($results as $result)
               <tr>
                    <td>{{$result->exam->name}}</td>
                    <td>{{$result->student->name}}</td>
                    <td>@php echo count(unserialize($result->right)); @endphp</td>
                    <td>@php echo count(unserialize($result->wrong)); @endphp</td>
                    <td><a href="{{route('result.sheet', [$result->id ,$result->exam->id, $result->student->id])}}"><button>View</button></a></td>
               </tr>
               @endforeach
              </tbody>
          </table>
        </div>
    </div>
@stop

resources/views/teachers/resultsheet.blade.php
@extends('adminlte::page')

@section('content')
    <div class="card">
        <div class="card-body">
            @foreach($questions as $question )
              @php
                 $current_question = \App\Question::with('summernote')->find($question);
                 $current_options = unserialize( $current_question->options);
                 $correct_option = unserialize($current_question->correct);
                 $letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i','j', 'k'];
              @endphp
              @if(!in_array($question, $no_response))
                  @if(in_array($question, $right))
                        @php
                            $response = 'right';
                            unset($answered_option)
                        @endphp
                  @endif

                  @if(in_array($question, $wrong))
                          @php
                              foreach ($original_responses as $original_response){
                                  if ($original_response[0] == $question){
                                      $answered_option = $original_response[1];
                                      break;
                                  }
                              }
                              $response = 'Wrong';
                          @endphp
                  @endif
                @else
                 @php
                     $response = 'No response';
                     unset($answered_option)
                 @endphp
              @endif

            <table class="table">
                <thead>
                  <tr>
                      <td>Question</td>
                      <td>Options</td>
                      <td>Status</td>
                      <td>Correct Option</td>
                      <td>Answered Option</td>
                  </tr>
                </thead>
                <tbody>
                 <tr>
                     <td>
                         <h2>{!! $current_question->summernote->instructions!!}</h2>
                     </td>
                     <td>@php $i=0; @endphp
                         @foreach($current_options as $option)
                             @php $i++; @endphp
                             <ul>
                                 <li> {{$letters[$i-1]}}: {{$option}}</li>
                             </ul>
                         @endforeach
                     </td>
                     <td>{{$response}}</td>
                     <td><h6>Option: {{$letters[$correct_option[0]]}}</h6></td>
                     <td>
                         @if(isset($answered_option))
                             <h6>Option: {{$answered_option}}</h6>
                         @endif
                     </td>
                 </tr>
                </tbody>
            </table>
            @endforeach
        </div>
    </div>
@stop