routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth:web','role:Admin|Teacher'])->group(function() {
    Route::resource('/groups', GroupController::class);
    Route::resource('/exams', ExamController::class);
    Route::get('/students', 'StudentController@index')->name('students.index');
    Route::get('/student/create' , 'StudentController@create')->name('student.create');
    Route::post('student/approval/{student}', 'StudentController@approval');
    Route::post('student/store', 'StudentController@store')->name('student.store');

    Route::post('/exams/activation/{id}', 'ExamController@activation')->name('exams.activation');
    Route::get('/exams/manage/{id}', 'ExamController@manage')->name('exams.manage');
    Route::post('/exams/manage/question/list/{id?}', 'ExamController@questionList')->name('exams.manage.question.list');
    Route::post('/exams/assign-question', 'ExamController@assignQuestion')->name('exams.assignQuestion');

    Route::get('/question/create', 'QuestionController@create')->name('question.create');
    Route::post('/question/save', 'QuestionController@save')->name('question.save');
    Route::post('question/unset/{id}', 'QuestionController@unset')->name('question.unset');
    Route::get('/question/{id}/edit', 'QuestionController@edit')->name('question.edit');
    Route::post('/question/update/{question}', 'QuestionController@update')->name('question.update');
    Route::get('/question/select/{subject}', 'QuestionController@select')->name('question.select');
    Route::post('/question/set/{question}', 'QuestionController@set')->name('question.set');
    Route::delete('/question/destroy/{question}', 'QuestionController@destroy')->name('question.destroy');

    Route::get('/questions', 'QuestionController@index')->name('questions.index');
    Route::post('/select/question/set/{exam}', 'ExamController@selectQuestionSet')->name('select.question.set');

    Route::resource('/banks', BanksController::class);
    Route::get('/banks/question/select/{subject}', 'BanksController@select')->name('banks.question.select');
    Route::post('banks/question/unset/{id}', 'BanksController@unset');
    Route::post('/banks/question/unsetWhileCreate/{question}', 'BanksController@unsetWhileCreate');
    Route::post('banks/question/set/while/edit/{bank}/{question}', 'BanksController@setWhileEdit');
    Route::post('banks/question/set/while/create/{question}', 'BanksController@setWhileCreate');
    Route::get('/banks/question/select/while/create/{subject}', 'BanksController@selectWhileCreate');

    Route::post('exam/manage/question/save/', 'ExamController@examManageQuestionSave')->name('exam.manage.question.save');
    Route::post('bank/rename/{bank}', 'BanksController@rename');
    Route::get('/banks/question/select/while/edit/{bank}/{subject}', 'BanksController@selectWhileEdit');

    Route::get('/exam-students', 'StudentController@examStudents');
    Route::get('/exam-students/delete/{examStudent}', 'StudentController@examStudentsDelete');
    Route::get('/exam-students/edit/form/{examStudent}', 'StudentController@examStudentEditForm')->name('student-exam.edit.form');
    Route::get('/student/unset/from/list/{exam}/{student}', 'StudentController@studentUnsetFromList')->name('student.unset.from.list');
    Route::get('/student/add/to/exams', 'StudentController@addExamForm');
    Route::post('/student/list/from/institution/{institution}', 'StudentController@studentListFromInstitution');
    Route::post('/student/attach/to/exam/{id}', 'StudentController@attachToExam');

    Route::get('/results', 'ResultController@index');
    Route::get('/result/from/teachers/panel/{exam}', 'ResultController@resultFromTeachersPanel')->name('result.teacher');
    Route::get('/result/sheet/from/teachers/panel/{result}/{exam}/{user}', 'ResultController@resultSheetTeachersPanel')->name('result.sheet');

    Route::get('/competitions', 'CompetitionController@index');
    Route::get('/competitions/create', 'CompetitionController@create')->name('competitions.create');
    Route::post('/competitions/store', 'CompetitionController@store')->name('competitions.store');
    Route::get('/competitions/{competition}', 'CompetitionController@show')->name('competition.show');
    Route::get('/competitions/edit/{competition}', 'CompetitionController@edit')->name('competition.edit');
    Route::post('/competitions/update/{competition}', 'CompetitionController@update')->name('competition.update');
    Route::get('/competitions/delete/{competition}', 'CompetitionController@delete')->name('competition.delete');
    //Route::post('competitions/student/list/from/institution/{institution}', 'CompetitionController@studentList');
    Route::resource('/institutions', InstitutionController::class);
    Route::resource('/subjects', SubjectController::class);
});

Route::get('/register/students', 'Auth\RegisterController@showStudentRegisterForm');
Route::post('/register/students', 'Auth\RegisterController@createStudent');

Route::middleware(['auth:web','role:Admin'])->group(function() {
    Route::view('/admin', 'admin');
    Route::resource('teachers', TeacherController::class);
    Route::post('/teacher/activation/{teacher}', 'TeacherController@activation');
    Route::get('accessibility', 'AccessibilityController@index')->name('accessibility');
    Route::get('accessibility/edit/{role}', 'AccessibilityController@edit')->name('accessibility.edit');
    Route::post('accessibility/update/{role}', 'AccessibilityController@update')->name('accessibility.update');
    Route::get('permissions', 'AccessibilityController@permissions')->name('permissions');
    Route::get('add/permission', 'AccessibilityController@addPermission')->name('add.permission');
    Route::get('save/permission', 'AccessibilityController@savePermission')->name('save.permission');
    Route::get('permission/edit/{id}', 'AccessibilityController@editPermission')->name('edit.permission');
    Route::get('permission/update/{id}', 'AccessibilityController@updatePermission')->name('update.permission');
    Route::get('permission/delete/{id}', 'AccessibilityController@deletePermission')->name('delete.permission');
});

Route::middleware(['auth:web','role:Teacher|Admin|Student'])->group(function() {
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile/update/{role}/{id}', 'ProfileController@update')->name('profile.update');
});

Route::middleware(['auth:web','role:Student'])->group(function () {
    Route::get('/student', 'StudentController@getProfile')->name('profile');
    Route::get('/student/exam/attend/{exam}/{id}', 'StudentController@examAttend')->name('exam.attend');
    Route::post('result/create/{exam}/{id}', 'StudentController@resultCreate');
    Route::get('/student/results', 'StudentController@resultsList')->name('student.results');
    Route::get('/student/result/sheet/{result}/{exam}/{user}', 'StudentController@resultSheetStudentPanel')->name('student.result.sheet');
    Route::get('/student/competitions', 'StudentController@competitions');
});

//Exam enrollment
Route::get('enroll/exam/{examName}', function () {
    auth()->logout();
    return view('exams/enroll');
});
Route::post('enroll/student/frontend', 'ExamController@enrollStudentFrontend')->name('enroll.student.frontend');

//Competition enrollment
Route::get('enroll/competition/{competitionName}', function () {
    auth()->logout();
    return view('competitions/enroll');
});
Route::post('enroll/student/frontend/competition', 'CompetitionController@enrollStudentFrontend')->name('enroll.student.frontend.competition');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subject;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::all();
        return view('subjects.index', compact('subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subjects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'max:55'],
        ]);
        Subject::create([
            'name' => $request->name
        ]);
        \Session::flash('msg_success', 'New teacher has been created!');
        return redirect()->route('subjects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subjects = Subject::find($id);
        return view('subjects.edit', compact('subjects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'max:55'],
        ]);

        Subject::updateOrCreate( ['id'=>$id],['name'=>$request->name]);
        \Session::flash('msg_success', 'Subject has been updated!');
        return redirect('subjects');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Subject::find($id)->delete();
        return back();
    }
}

resources/views/subjects/create.blade.php
@extends('app')

@section('content')
<div class="card">
  <div class="card-body">
    <div class="row">
        <div class="col-md-6">
            <h3 style="font-family:verdana">Add Subject Name</h3>
            <form action="{{route('subjects.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <input class="form-control" name="name" required placeholder="Title">
                <br>
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
    </div>
  </div>
</div>
@stop

resources/views/subjects/edit.blade.php
@extends('app')

@section('content')
<div class="card">
  <div class="card-body">
    <div class="row">
        <div class="col-md-6">
            <h3 style="font-family:verdana">Edit Subject</h3>
            <form action="{{route('subjects.update', $subjects->id)}}" method="post" enctype="multipart/form-data">
                @csrf @method('PUT')
                <input class="form-control" name="name" value="{{$subjects->name}}" required placeholder="Title">
                <br>
                <button class="btn btn-primary" type="submit">Save</button>
            </form>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
    </div>
  </div>
</div>
@stop

resources/views/subjects/index.blade.php
@extends('app')

@section('content')
    <div class="card">
        @if (\Session::has('msg_success'))
        <div class="row">
                <div class="col-lg-10">
                    <div  class="alert ">
                        <strong>Success! </strong>{{ \Session::get('msg_success') }}
                    </div>
                </div>
                <div class="clearfix"></div>
        </div>    
        @endif
       
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-borderless">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th><a href="{{route('subjects.create')}}"><button class="btn btn-primary">Add New</button></a></th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="table-responsive">
                   <table class="table table-hover  mx-auto table-sm">
                       <thead>
                           <tr>
                               <th></th>
                               <th></th>
                               <th></th>
                               <th></th>
                               <th>Name</th>
                               <th>Actions</th>
                           </tr>
                       </thead>
                       <tbody>
                       @if($subjects->count() != 0)
                           @foreach($subjects as $subject)
                               <tr>
                                   <td></td>
                                   <td></td>
                                   <td></td>
                                   <td></td>
                                   <td>{{$subject->name}}</td>
                                   <td>
                                       <div class="btn-group" role="group" aria-label="Basic example">
                                           <form action="{{route('subjects.destroy', $subject->id)}}" method="post">
                                               @csrf @method('delete')
                                               <button class="btn btn-danger">Delete</button>
                                           </form>
                                           <form action="{{route('subjects.edit', $subject->id)}}" method="get">
                                               @csrf
                                               <button class="btn btn-info">Edit</button>
                                           </form>
                                       </div>
                                   </td>
                               </tr>
                           @endforeach
                       @else
                           <tr>
                               <td><h5>Please add some subjects first</h5></td>
                           </tr>
                       @endif
                       </tbody>
                   </table>
            </div>
        </div>
    </div>

@stop