routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth:web','role:Admin|Teacher'])->group(function() {
    Route::resource('/groups', GroupController::class);
    Route::resource('/exams', ExamController::class);
    Route::get('/students', 'StudentController@index')->name('students.index');
    Route::get('/student/create' , 'StudentController@create')->name('student.create');
    Route::post('student/approval/{student}', 'StudentController@approval');
    Route::post('student/store', 'StudentController@store')->name('student.store');

    Route::post('/exams/activation/{id}', 'ExamController@activation')->name('exams.activation');
    Route::get('/exams/manage/{id}', 'ExamController@manage')->name('exams.manage');
    Route::post('/exams/manage/question/list/{id?}', 'ExamController@questionList')->name('exams.manage.question.list');
    Route::post('/exams/assign-question', 'ExamController@assignQuestion')->name('exams.assignQuestion');

    Route::get('/question/create', 'QuestionController@create')->name('question.create');
    Route::post('/question/save', 'QuestionController@save')->name('question.save');
    Route::post('question/unset/{id}', 'QuestionController@unset')->name('question.unset');
    Route::get('/question/{id}/edit', 'QuestionController@edit')->name('question.edit');
    Route::post('/question/update/{question}', 'QuestionController@update')->name('question.update');
    Route::get('/question/select/{subject}', 'QuestionController@select')->name('question.select');
    Route::post('/question/set/{question}', 'QuestionController@set')->name('question.set');
    Route::delete('/question/destroy/{question}', 'QuestionController@destroy')->name('question.destroy');

    Route::get('/questions', 'QuestionController@index')->name('questions.index');
    Route::post('/select/question/set/{exam}', 'ExamController@selectQuestionSet')->name('select.question.set');

    Route::resource('/banks', BanksController::class);
    Route::get('/banks/question/select/{subject}', 'BanksController@select')->name('banks.question.select');
    Route::post('banks/question/unset/{id}', 'BanksController@unset');
    Route::post('/banks/question/unsetWhileCreate/{question}', 'BanksController@unsetWhileCreate');
    Route::post('banks/question/set/while/edit/{bank}/{question}', 'BanksController@setWhileEdit');
    Route::post('banks/question/set/while/create/{question}', 'BanksController@setWhileCreate');
    Route::get('/banks/question/select/while/create/{subject}', 'BanksController@selectWhileCreate');

    Route::post('exam/manage/question/save/', 'ExamController@examManageQuestionSave')->name('exam.manage.question.save');
    Route::post('bank/rename/{bank}', 'BanksController@rename');
    Route::get('/banks/question/select/while/edit/{bank}/{subject}', 'BanksController@selectWhileEdit');

    Route::get('/exam-students', 'StudentController@examStudents');
    Route::get('/exam-students/delete/{examStudent}', 'StudentController@examStudentsDelete');
    Route::get('/exam-students/edit/form/{examStudent}', 'StudentController@examStudentEditForm')->name('student-exam.edit.form');
    Route::get('/student/unset/from/list/{exam}/{student}', 'StudentController@studentUnsetFromList')->name('student.unset.from.list');
    Route::get('/student/add/to/exams', 'StudentController@addExamForm');
    Route::post('/student/list/from/institution/{institution}', 'StudentController@studentListFromInstitution');
    Route::post('/student/attach/to/exam/{id}', 'StudentController@attachToExam');

    Route::get('/results', 'ResultController@index');
    Route::get('/result/from/teachers/panel/{exam}', 'ResultController@resultFromTeachersPanel')->name('result.teacher');
    Route::get('/result/sheet/from/teachers/panel/{result}/{exam}/{user}', 'ResultController@resultSheetTeachersPanel')->name('result.sheet');

    Route::get('/competitions', 'CompetitionController@index');
    Route::get('/competitions/create', 'CompetitionController@create')->name('competitions.create');
    Route::post('/competitions/store', 'CompetitionController@store')->name('competitions.store');
    Route::get('/competitions/{competition}', 'CompetitionController@show')->name('competition.show');
    Route::get('/competitions/edit/{competition}', 'CompetitionController@edit')->name('competition.edit');
    Route::post('/competitions/update/{competition}', 'CompetitionController@update')->name('competition.update');
    Route::get('/competitions/delete/{competition}', 'CompetitionController@delete')->name('competition.delete');
    //Route::post('competitions/student/list/from/institution/{institution}', 'CompetitionController@studentList');
    Route::resource('/institutions', InstitutionController::class);
    Route::resource('/subjects', SubjectController::class);
});

Route::get('/register/students', 'Auth\RegisterController@showStudentRegisterForm');
Route::post('/register/students', 'Auth\RegisterController@createStudent');

Route::middleware(['auth:web','role:Admin'])->group(function() {
    Route::view('/admin', 'admin');
    Route::resource('teachers', TeacherController::class);
    Route::post('/teacher/activation/{teacher}', 'TeacherController@activation');
    Route::get('accessibility', 'AccessibilityController@index')->name('accessibility');
    Route::get('accessibility/edit/{role}', 'AccessibilityController@edit')->name('accessibility.edit');
    Route::post('accessibility/update/{role}', 'AccessibilityController@update')->name('accessibility.update');
    Route::get('permissions', 'AccessibilityController@permissions')->name('permissions');
    Route::get('add/permission', 'AccessibilityController@addPermission')->name('add.permission');
    Route::get('save/permission', 'AccessibilityController@savePermission')->name('save.permission');
    Route::get('permission/edit/{id}', 'AccessibilityController@editPermission')->name('edit.permission');
    Route::get('permission/update/{id}', 'AccessibilityController@updatePermission')->name('update.permission');
    Route::get('permission/delete/{id}', 'AccessibilityController@deletePermission')->name('delete.permission');
});

Route::middleware(['auth:web','role:Teacher|Admin|Student'])->group(function() {
    Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile/update/{role}/{id}', 'ProfileController@update')->name('profile.update');
});

Route::middleware(['auth:web','role:Student'])->group(function () {
    Route::get('/student', 'StudentController@getProfile')->name('profile');
    Route::get('/student/exam/attend/{exam}/{id}', 'StudentController@examAttend')->name('exam.attend');
    Route::post('result/create/{exam}/{id}', 'StudentController@resultCreate');
    Route::get('/student/results', 'StudentController@resultsList')->name('student.results');
    Route::get('/student/result/sheet/{result}/{exam}/{user}', 'StudentController@resultSheetStudentPanel')->name('student.result.sheet');
    Route::get('/student/competitions', 'StudentController@competitions');
});

//Exam enrollment
Route::get('enroll/exam/{examName}', function () {
    auth()->logout();
    return view('exams/enroll');
});
Route::post('enroll/student/frontend', 'ExamController@enrollStudentFrontend')->name('enroll.student.frontend');

//Competition enrollment
Route::get('enroll/competition/{competitionName}', function () {
    auth()->logout();
    return view('competitions/enroll');
});
Route::post('enroll/student/frontend/competition', 'CompetitionController@enrollStudentFrontend')->name('enroll.student.frontend.competition');

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    protected $guarded = [];
}

resources/views/banks/create.blade.php
@extends('app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                        <div class="row">
                            <h4 class="col-md-2">Question Set</h4>
                            <input required class="col-md-6" name="name" class="form-control" id="name">
                            <h6 id="msg"></h6>
                        </div>
                        <br>
                        <div class="row">
                            <h4 class="col-md-2">Subject:</h4>
                            <select class="col-md-6" title="subject" name="subject_id" id="select">
                                <option disabled selected>Select</option>
                                @foreach($subjects as  $subject)
                                    <option value="{{$subject->id}}"> {{$subject->name}} </option>
                                @endforeach
                            </select>
                        </div>
                        <br>
                        <div class="card">
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <td>Question</td>
                                        
                                        <td>Marks</td>
                                        <td>Negative Marks</td>
                                        <td>Subject</td>
                                        
                                        <td>Select</td>
                                    </tr>
                                    </thead>
                                    <tbody id="question_selector">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h5>Selected Questions List</h5>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <td>Question</td>
                                        
                                        <td>Marks</td>
                                        <td>Negative Marks</td>
                                        <td>Subject</td>
                                        
                                        <td>Actions</td>
                                    </tr>
                                    </thead>
                                    <tbody id="tbody">
                                    @if(isset($questions))
                                        @foreach($questions as $question)
                                            <tr id="_{{$question->id}}">
                                                <td>{!!$question->summernote->instructions!!}</td>

                                                <td>{{$question->mark}}</td>
                                                <td>{{$question->negative}}</td>
                                                <td>{{$question->subject->name}}</td>
                                                
                                                <td>
                                                    <div class="row">
                                                        <div class="col-sm-3">
                                                            <button value="{{$question->id}}" class="unset btn btn-danger">Unset</button>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <td><h6>Please add some questions first</h6></td>
                                        </tr>
                                    @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#select').change(function(){
                $.ajax({
                    type:'GET',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url:'{{url('')}}/banks/question/select/while/create/'+$(this).val(),
                    data:{name: $('#name').val()},
                    success:function(data) {
                        $("#question_selector").html(data.msg);
                    }
                })
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#question_selector').change(function(){
                $.ajax({
                    type:'POST',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url:'{{url('')}}/banks/question/set/while/create/'+$('input[name="question_id"]:checked').val(),
                    data:{name: $('#name').val()},
                    success:function(data) {
                        $('#select').val('select').prop('selected', true);
                        $("#question_selector").html(' ');
                        $('#msg').html(data.message);
                        $("#tbody").html(data.list);
                    }
                })
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function(){
            //$('.unset').click(function(){
            $(document).on("click", ".unset", function(){
                    $.ajax({
                        type:'POST',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        url:'{{url('')}}/banks/question/unsetWhileCreate/'+$(this).val(),
                        data:{name: $('#name').val()},
                        success:function(data) {
                            $('#select').val('select').prop('selected', true);
                            $("#question_selector").html(data.msg);
                            $("#tbody").html(data.message);
                        }
                    })
                }
            );
        });
    </script>
@stop

resources/views/banks/edit.blade.php
@extends('app')

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h1 id="top">{{$bank->name}}</h1>
                        <div class="row">
                            <h4 class="col-md-2">Question Set</h4>
                                <form action="{{url('bank/rename', [$bank->id])}}" method="post">
                                    <input required class="col-md-6" name="name" class="form-control" id="name" value="{{$bank->name}}">
                                    @csrf
                                    <button type="submit" class="btn btn-info">Rename</button>
                                </form>
                            </div>
                        <br>
                        <div class="row">
                            <h4 class="col-md-2">Subject:</h4>
                            <select class="col-md-6" title="subject" name="subject_id" id="select">
                                <option selected disabled>Select</option>
                                @foreach($subjects as  $subject)
                                    <option value="{{$subject->id}}"> {{$subject->name}} </option>
                                @endforeach
                            </select>
                        </div>
                        <br>
                        <div class="card">
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <td>Question</td>
                                        
                                        <td>Marks</td>
                                        <td>Negative Marks</td>
                                        <td>Subject</td>
                                        
                                        <td>Select</td>
                                    </tr>
                                    </thead>
                                    <tbody id="question_selector">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <h5>Selected Questions List</h5>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <td>Question</td>
                                        
                                        <td>Marks</td>
                                        <td>Negative Marks</td>
                                        <td>Subject</td>
                                        
                                        <td>Actions</td>
                                    </tr>
                                    </thead>
                                    <tbody id="tbody">
                                    @if(isset($questions))
                                        @foreach($questions as $question)
                                            <tr id="_{{$question->id}}">
                                                <td>{!!$question->summernote->instructions!!}</td>

                                                <td>{{$question->mark}}</td>
                                                <td>{{$question->negative}}</td>
                                                <td>{{$question->subject->name}}</td>
                                                
                                                <td>
                                                    <div class="row">
                                                        <div class="col-sm-3">
                                                            <button value="{{$question->id}}" class="unset btn btn-danger">Unset</button>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <td><h1>Please add some questions first</h1></td>
                                        </tr>
                                    @endif
                                    </tbody>
                                </table>
                            </div>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script type="text/javascript">
        $(document).ready(function(){
            $('#select').change(function(){
                $.ajax({
                    type:'GET',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url:'{{url('')}}/banks/question/select/while/edit/{{$bank->id}}/'+$(this).val(),
                    data:{},
                    success:function(data) {
                        $("#question_selector").html(data.msg);
                    }
                })
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#question_selector').change(function(){
                $.ajax({
                    type:'POST',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    url:'{{url('')}}/banks/question/set/while/edit/{{$bank->id}}/'+$('input[name="question_id"]:checked').val(),
                    data:{name: $('#name').val()},
                    success:function(data) {
                        $('#top').html(data.name);
                        $('#select').val('select').prop('selected', true);
                        $("#question_selector").html(' ');
                        $("#tbody").html(data.list);
                    }
                })
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            //$('.unset').click(function(){
            $(document).on("click", ".unset", function(){
                    $.ajax({
                        type:'POST',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        url:'{{url('')}}/banks/question/unset/'+$(this).val(),
                        data:{bank_id: "{{$bank->id}}" },
                        success:function(data) {
                            $('#select').val('select').prop('selected', true);
                            $("#question_selector").html(data.msg);
                            $("#tbody").html(data.message);
                        }
                    })
                }
            );
        });
    </script>
@stop

resources/views/banks/index.blade.php
@extends('app')

@section('header')
 Question Banks
@stop

@section('content')
    <div class="card">
        <div class="card-body">
        @if (\Session::has('msg_success'))
        <div class="row">
            <div class="col-lg-10">
                <div class="alert ">
                    <strong>Success! </strong>{{ \Session::get('msg_success') }}
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        @endif
        <div class="table-responsive">
            <table class="table table-borderless">
                <thead>
                    <tr> 
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th><a href="{{route('banks.create')}}"><button class="btn btn-primary btn-block">Add New</button></a></th>
                    </tr>
                </thead>
            </table>
        </div>
       
                 <div class="table-responsive">
                    <table class="table table-hover mx-auto table-sm">
                        <thead class="thead-light">
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>Title</th>
                            <th>Number of questions</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if($banks->count() != 0)
                            @foreach($banks as $bank)
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>{{$bank->name}}</td>
                                    <td>
                                        @php
                                            $unserialized = unserialize($bank->question_ids);
                                            $questions = count($unserialized);
                                        @endphp
                                        {{$questions}}
                                    </td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                                <form action="{{route('banks.destroy', $bank->id)}}" method="post">
                                                    @csrf @method('delete')
                                                    <button class="btn btn-danger">Delete</button>
                                                </form>

                                                <form action="{{route('banks.edit', $bank->id)}}" method="get">
                                                    @csrf
                                                    <button class="btn btn-info">Edit</button>
                                                </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td><h6>Please add some questions first</h6></td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                 </div>   
                
    </div>
</div>
@stop